set error output

diff --git a/.github/workflows/function-beat.yml b/.github/workflows/function-beat.yml
--- a/.github/workflows/function-beat.yml
+++ b/.github/workflows/function-beat.yml
@@ -16,7 +16,8 @@ jobs:
     - name: Deploy the functionbeat
       id: deploy
       continue-on-error: true
-      run: ./functionbeat -v -e -d "*" deploy my-fucking-functionbeat-logs && echo "::set-output name=functionbeat_status::success" ||   echo "::set-output name=functionbeat_status::failure"
+      # run: ./functionbeat -v -e -d "*" deploy my-fucking-functionbeat-logs && echo "::set-output name=functionbeat_status::success" ||   echo "::set-output name=functionbeat_status::failure"
+      run: if [[ $(./functionbeat -v -e -d "*" deploy my-fucking-functionbeat-logs)  > 0 ]] ; then  echo "::set-output name=functionbeat_status::success"; else echo "::set-output name=functionbeat_status::failure" ; fi
       working-directory: functionbeat
 
     - name: Dump steps context
